"""Model discrepancy — doc 05 §4, doc 11 WBS 3.6, doc 00 §5.1 criterion S4.

## The measurement that made this necessary

Closed-loop recovery of ``Gamma_E``, measured on the reference machine:

    T0   error 3.6e-05   90 % interval +/-0.02 %   truth covered: yes
    T1   error 2.6e-04   90 % interval +/-0.11 %   truth covered: yes
    T2   error 3.6e-01   90 % interval +/-0.29 %   truth covered: NO

The T2 posterior is overconfident by a factor of about 126. doc 00 §5.1's S4 requires the
empirical coverage of a credible interval to match its nominal level, and states the
consequence: "An uncalibrated posterior is worse than no posterior." T2 therefore fails a
stated success criterion, and this module is the response.

## Why it happens

A Laplace posterior propagates *parameter* uncertainty **given the model**. The likelihood
asserts ``y = F(theta) + eps`` with ``eps`` the measurement noise, and has no vocabulary for
``F`` being the wrong function. At T2 the truth is generated by L1 and inverted with L0, and
L0 fits an L1-generated spectrum *well* by moving ``n_0`` and ``T_e`` — so the residual is
small, so the likelihood is sharply peaked, around the wrong point.

**A misspecified model yields a tight posterior on a wrong answer.** This is a property of
the likelihood rather than a defect in the optimiser, and no amount of better optimisation
touches it.

## What this does — and what it explicitly does not

Kennedy & O'Hagan (2001) write ``y = F(theta) + delta + eps`` and give ``delta`` a GP prior,
inferring it jointly with ``theta``. That is a substantial build, and ``delta`` is notoriously
confounded with ``theta``: the joint problem carries identifiability pathologies of its own,
which is a poor trade when the project already has an identifiability problem to report.

This module implements the affordable half: ``delta`` enters as additional **variance**
rather than as an inferred function,

    Sigma_total = Sigma_noise + Sigma_discrepancy

**This makes the interval honest. It does not make the estimate accurate.** The bias at T2
is untouched; the interval grows until it contains the truth.
``test_the_estimate_is_still_biased_which_is_reported_not_hidden`` exists to contradict the
opposite reading, because "we added a discrepancy term" sounds like an accuracy fix and is
not one. Accuracy comes from breaking the degeneracy that lets a wrong ``theta`` fit so
well — a second channel, a line ratio — and that is separate work.

## Estimating it without touching the truth

The truth is sealed (doc 05 §7), so the discrepancy scale cannot be calibrated against it —
and reaching for it would be the inverse crime that module exists to prevent. It *can* be
measured between **our own models**: evaluate the inversion's model and a higher-fidelity
one over draws from the prior and take the spread of their disagreement. That is a statement
about the model family, needing no access to the answer.
:func:`estimate_hierarchy_discrepancy` accordingly takes two model callables and **no truth
argument at all** — the signature is the guarantee, not a convention.

Stated limitation, because it bounds what any coverage number derived from this can mean:
the L0-vs-L1 spread is a **lower bound** on L0-vs-reality. Calibrating against it corrects
only for structural error the hierarchy already knows about. A model wrong in a way every
member of the hierarchy is wrong in stays invisible, and no internal comparison could
reveal it. That is an argument for the L2 and experimental anchors, not against this.

## Why the discrepancy must be CORRELATED, not per-channel independent

This is the subtlety that makes or breaks the correction, and the first implementation here
got it wrong before a test caught it.

Model discrepancy is **systematic**. If L0 gets the excitation physics of a line wrong, it
gets it wrong the same way in every channel of every exposure — it is a coherent offset, not
a fluctuation. Entered as independent per-channel variance it averages down like
``1 / sqrt(N_channels)`` in the fit, exactly as noise does, and the interval ends up too
narrow by that factor. Measured on the 12-channel case in the tests: a coherent bias of 0.5
produced a diagonal-inflated interval of 0.145 (still excluding the truth) against a
correctly correlated 0.500 (covering it) — under-inflation by ``sqrt(12) = 3.46``.

So the discrepancy enters as a **rank-one** contribution ``(f y)(f y)^T`` in the fully
coherent limit, which does not average down with more channels, and
:attr:`FractionalDiscrepancy.coherence` interpolates to the independent case for the part of
the structural error that genuinely is channel-local. The default is full coherence, because
that is what a wrong forward model actually produces.

Note the irony worth recording: adding a discrepancy term *diagonally* would have produced a
slightly wider interval, a coverage number that improved without passing, and every
appearance of a fix. It is the same failure as T2 itself — a plausible correction that is
quietly the wrong shape.

## Why the inflation is multiplicative

Structural error in a forward model scales with the signal: getting the excitation physics
of a line wrong misplaces it by a *fraction*, not by a fixed number of counts. An absolute
floor would swamp the faint channels and vanish on the bright ones, which is backwards for
a spectrum spanning orders of magnitude. So :class:`FractionalDiscrepancy` is multiplicative,
and per-channel rather than scalar, because a model can be structurally sound on one line
and badly wrong on the next.
"""

from __future__ import annotations

import math
from collections.abc import Callable, Sequence
from dataclasses import dataclass
from typing import Protocol, runtime_checkable

import numpy as np
from numpy.typing import ArrayLike, NDArray

__all__ = [
    "DiscrepancyModel",
    "EmpiricalDiscrepancy",
    "FractionalDiscrepancy",
    "NoDiscrepancy",
    "estimate_empirical_discrepancy",
    "estimate_hierarchy_discrepancy",
    "inflated_covariance",
    "inflated_variance",
]

type FloatArray = NDArray[np.float64]
type ForwardModel = Callable[[NDArray[np.float64]], NDArray[np.float64]]


@runtime_checkable
class DiscrepancyModel(Protocol):
    """Additional variance attributable to the forward model being wrong.

    A protocol so that a discrepancy model is a **plugin** in the sense of doc 00 §5.1's
    E1: a new one is addable without touching any inference engine. It is deliberately the
    narrowest possible interface — a variance per channel, given a prediction — because
    anything richer would start to duplicate the likelihood's job.
    """

    def variance(self, prediction: ArrayLike) -> FloatArray:
        """Discrepancy variance per channel, in the observable's own units squared.

        The **marginal** variance, i.e. the diagonal of :meth:`covariance`. Useful for
        reporting; not sufficient for a fit, because it discards the correlation that is the
        whole point — see the module docstring.
        """
        ...

    def covariance(self, prediction: ArrayLike) -> FloatArray:
        """Full discrepancy covariance, shape ``(n, n)``.

        This is what a likelihood must use. Structural error is coherent across channels, so
        the off-diagonal terms are not a refinement — omitting them under-inflates the
        interval by up to ``sqrt(n)``.
        """
        ...


@dataclass(frozen=True, slots=True)
class NoDiscrepancy:
    """The model is assumed exactly correct — T0 and T1's configuration.

    Returns exactly zero rather than something small. T0 and T1 already cover their truths
    (0.02 % and 0.11 % intervals), so any perturbation of them is a regression, and "exactly
    inert" is a property a test can assert where "negligible" is not.
    """

    def variance(self, prediction: ArrayLike) -> FloatArray:
        return np.zeros_like(np.asarray(prediction, dtype=np.float64))

    def covariance(self, prediction: ArrayLike) -> FloatArray:
        size = np.asarray(prediction, dtype=np.float64).size
        return np.zeros((size, size), dtype=np.float64)


@dataclass(frozen=True, slots=True)
class FractionalDiscrepancy:
    """Structural error as a fraction of the predicted signal, per channel.

    Attributes:
        fraction: Fractional structural error. A scalar applies to every channel; an array
            gives one per channel, which is the point — see the module docstring on why
            pooling across a spectrum is wrong.
        coherence: Share of the discrepancy variance that is coherent across channels, in
            ``[0, 1]``. Defaults to fully coherent, because a wrong forward model is wrong
            the same way everywhere; the independent remainder exists for structural error
            that genuinely is channel-local (a single mis-tabulated transition, say).
            Lowering this is what silently under-inflates the interval — see the module
            docstring for the measured factor.
    """

    fraction: float | FloatArray
    coherence: float = 1.0

    def __post_init__(self) -> None:
        values = np.asarray(self.fraction, dtype=np.float64)
        if np.any(values < 0.0):
            raise ValueError(
                f"a discrepancy fraction is a magnitude and cannot be negative, got "
                f"{self.fraction!r}. A negative entry would subtract variance and produce "
                f"an interval narrower than the noise alone allows."
            )
        if not 0.0 <= self.coherence <= 1.0:
            raise ValueError(
                f"coherence is a share of the discrepancy variance and must lie in [0, 1], "
                f"got {self.coherence}"
            )

    def _scale(self, prediction: ArrayLike) -> FloatArray:
        """``f * y`` — the discrepancy standard deviation per channel."""
        predicted = np.asarray(prediction, dtype=np.float64)
        return np.asarray(np.asarray(self.fraction, dtype=np.float64) * predicted)

    def variance(self, prediction: ArrayLike) -> FloatArray:
        return np.asarray(self._scale(prediction) ** 2)

    def covariance(self, prediction: ArrayLike) -> FloatArray:
        """``coherence * (f y)(f y)^T + (1 - coherence) * diag((f y)^2)``.

        The diagonal is ``(f y)^2`` for any coherence, so :meth:`variance` and this agree on
        the marginals; the coherence only redistributes the off-diagonal mass. That is
        deliberate — it means a reported per-channel uncertainty does not change when the
        correlation assumption does, and only the *joint* inference feels it.
        """
        scale = self._scale(prediction)
        coherent = np.outer(scale, scale)
        independent = np.diag(scale**2)
        return np.asarray(self.coherence * coherent + (1.0 - self.coherence) * independent)


def inflated_variance(
    noise_variance: ArrayLike, *, prediction: ArrayLike, discrepancy: DiscrepancyModel
) -> FloatArray:
    """``Sigma_noise + Sigma_discrepancy``, per channel.

    Added in **variance**, not in standard deviation: the two error sources are independent,
    so they combine in quadrature. Adding the sigmas instead would over-inflate by up to a
    factor of two, and — being approximately right — would be unlikely to be caught by
    inspection.
    """
    noise = np.asarray(noise_variance, dtype=np.float64)
    extra = np.asarray(discrepancy.variance(prediction), dtype=np.float64)
    if extra.shape != noise.shape:
        raise ValueError(
            f"discrepancy variance shape {extra.shape} does not match the noise variance "
            f"shape {noise.shape}; they describe the same channels and must align."
        )
    return np.asarray(noise + extra, dtype=np.float64)


def inflated_covariance(
    noise_variance: ArrayLike, *, prediction: ArrayLike, discrepancy: DiscrepancyModel
) -> FloatArray:
    """``diag(Sigma_noise) + Sigma_discrepancy`` — the full covariance a likelihood needs.

    The measurement noise stays diagonal (independent per channel, which it is); the
    discrepancy does not. Using :func:`inflated_variance` in a fit instead of this discards
    the correlation and under-inflates the interval by up to ``sqrt(n)`` — see the module
    docstring for the measured case.
    """
    noise = np.asarray(noise_variance, dtype=np.float64)
    extra = np.asarray(discrepancy.covariance(prediction), dtype=np.float64)
    if extra.shape != (noise.size, noise.size):
        raise ValueError(
            f"discrepancy covariance shape {extra.shape} does not match a noise variance of "
            f"{noise.size} channels; they describe the same channels and must align."
        )
    return np.asarray(np.diag(noise) + extra, dtype=np.float64)


def estimate_hierarchy_discrepancy(
    *,
    low_fidelity: ForwardModel,
    high_fidelity: ForwardModel,
    thetas: Sequence[NDArray[np.float64]],
) -> FractionalDiscrepancy:
    """Estimate the structural error between two models of the same observable.

    Note what is **absent** from this signature: any truth, any observation, any sealed
    value. The estimate is a property of the model family alone, which is what makes it
    usable inside a closed loop without committing the inverse crime doc 05 §7 describes.

    The statistic is the root-mean-square *relative* difference per channel, taken over the
    supplied parameter draws:

        f_k = sqrt( mean_i [ (high_k(theta_i) - low_k(theta_i)) / low_k(theta_i) ]^2 )

    RMS rather than mean absolute, because it is a variance being estimated and the
    quadratic statistic is the one that composes correctly in
    :func:`inflated_covariance`. Relative to the **low**-fidelity prediction, and that
    choice is forced rather than aesthetic: at inference time the only prediction
    available is the low-fidelity model's, so the fraction is multiplied by ``F_low``.
    Defining it against ``F_high`` would reproduce the discrepancy scaled by
    ``F_low / F_high`` — right to first order, wrong exactly where the models differ
    most, which is the regime the correction exists for.

    Args:
        low_fidelity: The model the inversion actually uses (L0 here).
        high_fidelity: A better model of the same observable (L1, or L2 when affordable).
        thetas: Parameter draws to compare over. Draw them from the **prior**, not around a
            point estimate: the discrepancy has to cover the region the posterior might
            explore, and a spread taken at one theta would understate it everywhere else.

    Returns:
        A :class:`FractionalDiscrepancy` with one fraction per channel.
    """
    if len(thetas) == 0:
        raise ValueError(
            "estimating a discrepancy needs at least one parameter draw; with none there is "
            "nothing to compare and a zero fraction would silently disable the correction"
        )

    squared: list[FloatArray] = []
    for theta in thetas:
        low = np.asarray(low_fidelity(theta), dtype=np.float64)
        high = np.asarray(high_fidelity(theta), dtype=np.float64)
        if low.shape != high.shape:
            raise ValueError(
                f"the two models returned different shapes ({low.shape} and {high.shape}); "
                f"they must predict the same channels for the difference to mean anything"
            )
        # Where the low-fidelity prediction vanishes there is no scale to be relative to,
        # and a channel the inversion predicts nothing in carries no information either way.
        relative = np.divide(high - low, low, out=np.zeros_like(low), where=np.abs(low) > 0.0)
        squared.append(relative**2)

    return FractionalDiscrepancy(fraction=np.sqrt(np.mean(np.stack(squared), axis=0)))


@dataclass(frozen=True, slots=True)
class EmpiricalDiscrepancy:
    """Discrepancy covariance spanned by the *observed* model-error directions.

    Why this exists, when :class:`FractionalDiscrepancy` already inflates variance: a single
    coherent vector only de-weights the one direction it points along. Measured on T2, that
    is not enough. The L0-vs-L1 error is a **shape** mismatch across the emission profile,
    while the parameters move the profile's **amplitude**; the two are largely orthogonal, so
    a rank-one term left the parameter directions almost fully weighted. The large posterior
    eigenvalue fell only 1.66x where the rank-one algebra predicts ~300x if the discrepancy
    and the sensitivity were parallel — which is exactly the diagnostic that they are not.

    So the covariance is built from the model-error vectors themselves,

        Sigma_disc = (1 / N) sum_i  d_i d_i^T ,   d_i = y_high(theta_i) - y_low(theta_i)

    a rank-``N`` object that spans the directions the structural error is actually observed
    to take. Stored as its basis ``d_i / sqrt(N)`` rather than as the assembled matrix: over
    a 1024-pixel detector the matrix is a million entries, while the basis is ``N x 1024``
    and Woodbury turns every likelihood evaluation into an ``O(n k^2)`` operation.

    Attributes:
        basis: Shape ``(k, n)``. ``Sigma_disc = basis.T @ basis`` by construction, so the
            scaling by ``1/sqrt(N)`` belongs to whoever builds it.
    """

    basis: FloatArray

    def __post_init__(self) -> None:
        matrix = np.asarray(self.basis, dtype=np.float64)
        if matrix.ndim != 2:
            raise ValueError(f"a discrepancy basis must be (k, n), got shape {matrix.shape}")
        if not np.all(np.isfinite(matrix)):
            raise ValueError("the discrepancy basis contains non-finite entries")

    def variance(self, prediction: ArrayLike) -> FloatArray:
        """Marginal variance per channel — the diagonal of ``basis.T @ basis``.

        Ignores ``prediction``: unlike :class:`FractionalDiscrepancy` this is an *absolute*
        covariance measured in the observable's units, not a fraction of the signal, because
        it was estimated from actual differences rather than assumed proportional.
        """
        del prediction
        return np.asarray(np.sum(np.asarray(self.basis, dtype=np.float64) ** 2, axis=0))

    def covariance(self, prediction: ArrayLike) -> FloatArray:
        del prediction
        matrix = np.asarray(self.basis, dtype=np.float64)
        return np.asarray(matrix.T @ matrix)


def estimate_empirical_discrepancy(
    *,
    low_fidelity: ForwardModel,
    high_fidelity: ForwardModel,
    thetas: Sequence[NDArray[np.float64]],
) -> EmpiricalDiscrepancy:
    """Collect the model-error directions over a parameter sweep — doc 05 §4.

    Same discipline as :func:`estimate_hierarchy_discrepancy`: two model callables, **no
    truth argument**, so this cannot become an inverse crime. The difference is what is
    retained. That function collapses each difference to a per-channel magnitude and throws
    the direction away; this one keeps the vectors, which is what lets the resulting
    covariance overlap the directions the parameters actually move in.
    """
    if len(thetas) == 0:
        raise ValueError(
            "estimating a discrepancy needs at least one parameter draw; with none there is "
            "nothing to compare and an empty basis would silently disable the correction"
        )
    rows: list[FloatArray] = []
    for theta in thetas:
        low = np.asarray(low_fidelity(theta), dtype=np.float64).reshape(-1)
        high = np.asarray(high_fidelity(theta), dtype=np.float64).reshape(-1)
        if low.shape != high.shape:
            raise ValueError(
                f"the two models returned different shapes ({low.shape} and {high.shape})"
            )
        rows.append(high - low)
    return EmpiricalDiscrepancy(
        basis=np.asarray(np.stack(rows) / math.sqrt(len(rows)), dtype=np.float64)
    )
