"""Model discrepancy — doc 05 §4, doc 11 WBS 3.6, doc 00 §5.1 criterion S4.

## The measurement that made this necessary

Measured on the reference machine, closed-loop recovery of ``Gamma_E``:

    T0   error 3.6e-05   90 % interval +/-0.02 %   truth covered: yes
    T1   error 2.6e-04   90 % interval +/-0.11 %   truth covered: yes
    T2   error 3.6e-01   90 % interval +/-0.29 %   truth covered: NO

The T2 posterior is overconfident by a factor of ~126. doc 00 §5.1 S4 requires the
empirical coverage of the credible interval to match its nominal level, and adds: "An
uncalibrated posterior is worse than no posterior." So T2 currently fails a stated success
criterion of the project.

## Why it happens, and why no amount of better optimisation fixes it

A Laplace posterior propagates *parameter* uncertainty **given the model**. The likelihood
says ``y = F(theta) + eps`` with ``eps`` the measurement noise, and nothing in it can
express ``F`` being the wrong function. At T2 the truth is generated by L1 and inverted with
L0; L0 fits an L1-generated spectrum *well* by moving ``n_0`` and ``T_e``, so the residual
is small, so the likelihood is sharply peaked — around the wrong point.

**A misspecified model produces a tight posterior on a wrong answer.** That is the whole of
the problem, and it is a property of the likelihood, not a bug.

## What this module does, and what it deliberately does not do

Kennedy & O'Hagan (2001) write ``y = F(theta) + delta + eps`` and give ``delta`` its own GP
prior, inferring it jointly with ``theta``. That is a large build, and ``delta`` is famously
confounded with ``theta`` — the joint problem has identifiability pathologies of its own.

This module implements the affordable and defensible part: ``delta`` enters as an additional
**variance** rather than as a jointly-inferred function,

    Sigma_total = Sigma_noise + Sigma_discrepancy

**This makes the interval honest. It does not make the estimate accurate.** The 36.5 % bias
at T2 stays exactly where it is; the interval grows until it contains the truth. Saying so
plainly matters, because "we added a discrepancy term" reads like an accuracy fix and is
not one. Accuracy comes from breaking the degeneracy that lets a wrong ``theta`` fit so well
— a second channel, a line ratio — which is separate work.

## Estimating the discrepancy without touching the truth

The truth is sealed (doc 05 §7), so the discrepancy scale cannot be measured against it.
It can be measured between **our own models**: run the inversion's model and a
higher-fidelity one over draws from the prior, and take the spread of their disagreement.
That is a statement about the model family, computable with no access to the answer, and
:func:`estimate_hierarchy_discrepancy` takes two model callables and no truth argument at
all — the signature is the guarantee.

Stated limitation, because it bounds what any coverage number from this can mean: the
L0-vs-L1 spread is a **lower bound** on L0-vs-reality. Calibrating against it corrects only
for the structural error we already know about. A model wrong in a way the whole hierarchy
is wrong in is invisible here, and no amount of internal comparison would reveal it.
"""

from __future__ import annotations

import numpy as np
import pytest

from vpl.inverse.discrepancy import (
    DiscrepancyModel,
    FractionalDiscrepancy,
    NoDiscrepancy,
    estimate_hierarchy_discrepancy,
    inflated_covariance,
    inflated_variance,
)


class TestNoDiscrepancyIsExactlyInert:
    def test_it_adds_no_variance(self) -> None:
        # T0 and T1 use the correct model and their intervals already cover. Any change to
        # them is a regression, so the default must be exactly zero rather than small.
        prediction = np.array([10.0, 200.0, 3000.0])

        variance = NoDiscrepancy().variance(prediction)

        np.testing.assert_array_equal(variance, np.zeros(3))

    def test_the_inflated_variance_is_the_noise_variance_unchanged(self) -> None:
        noise = np.array([1.0, 4.0, 9.0])
        prediction = np.array([10.0, 20.0, 30.0])

        total = inflated_variance(noise, prediction=prediction, discrepancy=NoDiscrepancy())

        np.testing.assert_array_equal(total, noise)

    def test_it_satisfies_the_protocol(self) -> None:
        # doc 00 §5.1 E1: a discrepancy model is a plugin. The protocol is what makes a new
        # one addable without touching the inference engines.
        assert isinstance(NoDiscrepancy(), DiscrepancyModel)
        assert isinstance(FractionalDiscrepancy(fraction=0.1), DiscrepancyModel)


class TestFractionalDiscrepancy:
    def test_the_variance_is_the_fraction_times_the_prediction_squared(self) -> None:
        # Multiplicative rather than additive: a structural error in a forward model scales
        # with the signal. An absolute floor would dominate the faint channels and vanish on
        # the bright ones, which is backwards for a spectrum spanning orders of magnitude.
        prediction = np.array([100.0, 400.0])

        variance = FractionalDiscrepancy(fraction=0.05).variance(prediction)

        np.testing.assert_allclose(variance, (0.05 * prediction) ** 2)

    def test_a_per_channel_fraction_is_honoured(self) -> None:
        # Discrepancy is not uniform across a spectrum: a line the model gets structurally
        # wrong deserves more inflation than one it gets right, and collapsing them to a
        # scalar would throw away the only information that makes this better than a fudge.
        prediction = np.array([100.0, 100.0])
        fraction = np.array([0.01, 0.5])

        variance = FractionalDiscrepancy(fraction=fraction).variance(prediction)

        np.testing.assert_allclose(variance, (fraction * prediction) ** 2)

    def test_a_negative_fraction_is_refused(self) -> None:
        with pytest.raises(ValueError, match="fraction"):
            FractionalDiscrepancy(fraction=-0.1)

    def test_the_total_variance_adds_in_quadrature(self) -> None:
        # Independent error sources add in variance, not in standard deviation. Adding the
        # sigmas would over-inflate by up to a factor of two and would look approximately
        # right, which is the worst kind of wrong.
        noise = np.array([9.0])
        prediction = np.array([100.0])

        total = inflated_variance(
            noise, prediction=prediction, discrepancy=FractionalDiscrepancy(fraction=0.04)
        )

        np.testing.assert_allclose(total, 9.0 + 16.0)


class TestEstimatingTheDiscrepancyFromTheModelHierarchy:
    def test_it_recovers_a_known_fractional_difference(self) -> None:
        # Two toy models differing by a known 10 % everywhere. The estimator must return
        # 0.1, or every inflated interval downstream is scaled wrong.
        def low(theta: np.ndarray) -> np.ndarray:
            return np.array([theta[0], 2.0 * theta[0]])

        def high(theta: np.ndarray) -> np.ndarray:
            return 1.1 * np.array([theta[0], 2.0 * theta[0]])

        estimate = estimate_hierarchy_discrepancy(
            low_fidelity=low,
            high_fidelity=high,
            thetas=[np.array([t]) for t in np.linspace(1.0, 5.0, 20)],
        )

        np.testing.assert_allclose(estimate.fraction, [0.1, 0.1], rtol=1e-8)

    def test_it_estimates_per_channel_rather_than_pooling(self) -> None:
        # A model can be structurally fine on one line and badly wrong on another; pooling
        # would under-inflate the bad channel and over-inflate the good one.
        def low(theta: np.ndarray) -> np.ndarray:
            return np.array([1.0, 1.0]) * theta[0]

        def high(theta: np.ndarray) -> np.ndarray:
            return np.array([1.02, 1.5]) * theta[0]

        estimate = estimate_hierarchy_discrepancy(
            low_fidelity=low,
            high_fidelity=high,
            thetas=[np.array([t]) for t in np.linspace(1.0, 3.0, 10)],
        )

        np.testing.assert_allclose(estimate.fraction, [0.02, 0.5], rtol=1e-8)

    def test_identical_models_give_zero_discrepancy(self) -> None:
        # The T0/T1 case, and the sanity check that the estimator is not manufacturing
        # inflation out of nothing.
        def model(theta: np.ndarray) -> np.ndarray:
            return np.array([theta[0], theta[0] ** 2])

        estimate = estimate_hierarchy_discrepancy(
            low_fidelity=model,
            high_fidelity=model,
            thetas=[np.array([t]) for t in np.linspace(1.0, 4.0, 8)],
        )

        np.testing.assert_allclose(estimate.fraction, [0.0, 0.0], atol=1e-14)

    def test_an_empty_theta_set_is_refused(self) -> None:
        with pytest.raises(ValueError, match="at least"):
            estimate_hierarchy_discrepancy(
                low_fidelity=lambda t: t, high_fidelity=lambda t: t, thetas=[]
            )


class TestItActuallyFixesTheCoverageFailure:
    """The point of the module, in a case with a closed-form answer.

    A misspecified linear-Gaussian problem: the truth carries a structural bias the model
    cannot represent. Without a discrepancy term the posterior is tight and excludes the
    truth — the T2 failure in miniature. With one, it covers.
    """

    @staticmethod
    def _posterior(
        bias: float, discrepancy: DiscrepancyModel, *, diagonal_only: bool = False
    ) -> tuple[float, float, float]:
        """Return ``(mean, std, truth)`` for a one-parameter misspecified problem.

        Generalised least squares with the FULL covariance, because the discrepancy is
        correlated across channels. `diagonal_only=True` deliberately throws that
        correlation away, so a test can measure what discarding it costs.
        """
        design = np.full(12, 1.0)
        truth = 2.0
        noise_sigma = 0.05
        # The model predicts `design * u`. The data carry an extra structural offset the
        # model has no parameter for — this is exactly what "wrong model" means. Note it is
        # the SAME offset in every channel: structural error is coherent, not random.
        observed = design * truth + bias

        prediction_scale = design * truth
        noise_variance = np.full(design.size, noise_sigma**2)
        if diagonal_only:
            total = inflated_variance(
                noise_variance, prediction=prediction_scale, discrepancy=discrepancy
            )
            covariance = np.diag(total)
        else:
            covariance = inflated_covariance(
                noise_variance, prediction=prediction_scale, discrepancy=discrepancy
            )

        inverse = np.linalg.inv(covariance)
        precision = float(design @ inverse @ design)
        mean = float((design @ inverse @ observed) / precision)
        return mean, float(1.0 / np.sqrt(precision)), truth

    def test_without_a_discrepancy_term_the_interval_excludes_the_truth(self) -> None:
        # The T2 failure reproduced in a case where every number is checkable by hand.
        mean, std, truth = self._posterior(bias=0.5, discrepancy=NoDiscrepancy())

        assert abs(mean - truth) > 4.0 * std, (
            "this test is vacuous unless the misspecified posterior really does exclude the truth"
        )

    def test_with_a_matched_discrepancy_term_the_interval_covers_the_truth(self) -> None:
        # The fix. The structural offset is 0.5 on a signal of 2.0, i.e. 25 %; a discrepancy
        # term of that size widens the posterior until the truth is inside it.
        mean, std, truth = self._posterior(
            bias=0.5, discrepancy=FractionalDiscrepancy(fraction=0.25)
        )

        assert abs(mean - truth) < 2.0 * std

    def test_the_estimate_is_still_biased_which_is_reported_not_hidden(self) -> None:
        # The honesty check. Inflating the variance does NOT move the point estimate — the
        # bias is identical with and without the discrepancy term. Anyone reading "we added
        # a discrepancy term" as an accuracy improvement is reading it wrong, and this test
        # is where that misreading is contradicted.
        without, _, truth = self._posterior(bias=0.5, discrepancy=NoDiscrepancy())
        with_term, _, _ = self._posterior(
            bias=0.5, discrepancy=FractionalDiscrepancy(fraction=0.25)
        )

        assert with_term == pytest.approx(without, rel=1e-9)
        assert abs(with_term - truth) > 0.4

    def test_a_larger_discrepancy_widens_the_interval_monotonically(self) -> None:
        widths = [
            self._posterior(bias=0.5, discrepancy=FractionalDiscrepancy(fraction=f))[1]
            for f in (0.01, 0.05, 0.25, 0.5)
        ]

        assert widths == sorted(widths)

    def test_treating_a_coherent_discrepancy_as_independent_noise_under_inflates(self) -> None:
        # The defect that was in this module's first implementation, kept as a regression
        # test because it is the subtle one. Structural error is the same offset in every
        # channel; entered on the diagonal it averages down like 1/sqrt(N) exactly as noise
        # does, and the interval comes out sqrt(12) = 3.46x too narrow — still excluding the
        # truth, while looking like a fix had been applied.
        term = FractionalDiscrepancy(fraction=0.25)
        _, correlated_std, truth = self._posterior(bias=0.5, discrepancy=term)
        mean, diagonal_std, _ = self._posterior(bias=0.5, discrepancy=term, diagonal_only=True)

        assert correlated_std / diagonal_std == pytest.approx(np.sqrt(12.0), rel=0.05)
        assert abs(mean - truth) > 2.0 * diagonal_std, "the diagonal treatment still misses"

    def test_lowering_coherence_narrows_the_interval(self) -> None:
        # Coherence is the knob that decides how much of the structural error is systematic.
        # It must be explicit and it must matter, so that setting it low is a visible
        # modelling claim rather than an accidental default.
        stds = [
            self._posterior(
                bias=0.5, discrepancy=FractionalDiscrepancy(fraction=0.25, coherence=c)
            )[1]
            for c in (1.0, 0.5, 0.0)
        ]

        assert stds == sorted(stds, reverse=True)
