"""The MAP engine — doc 05 §5, doc 11 WBS 3.7.

## What these tests are for

An optimiser is easy to test badly. "It converged" and "the residual is small" are both
satisfied by an optimiser that has found the wrong answer confidently, and neither notices
the two errors that actually occur in this kind of code:

1. **The prior is dropped, or double-counted.** The objective is
   ``-(log L + log pi)``, in unconstrained space, *including the log-Jacobian*. Leaving the
   Jacobian out biases the estimate toward the transform's fixed point; adding it twice
   biases it away. Both still converge, smoothly, to something wrong.
2. **The gradient disagrees with the objective.** L-BFGS-B with a subtly wrong analytic
   gradient converges to a point that is not a stationary point of the function being
   reported. It is the single most common defect in hand-rolled inference code.

So the tests below are built around problems whose answer is known in closed form:
a Gaussian likelihood with a Gaussian prior has an analytically known posterior mode, and
the recovery must match it to optimiser tolerance rather than to eyeball. ADR-011 is this
project's standing reminder that self-consistent is not the same as correct.

## The T0 contract

doc 05 §7.2 defines T0 as "same model, no noise", expecting "recovery to numerical
tolerance", and is explicit that failing it means a bug rather than a result. The
noiseless-recovery test here is the engine's half of that contract: given data generated by
the very forward model being inverted, with no noise, the MAP must return the generating
parameters. If it cannot do that, nothing downstream means anything.
"""

from __future__ import annotations

import numpy as np
import pytest

from vpl.inverse.map import MapResult, maximum_a_posteriori, negative_log_posterior
from vpl.inverse.parameters import ControlParameters
from vpl.inverse.priors import default_control_prior


def _quadratic_forward(u: np.ndarray) -> np.ndarray:
    """A deliberately trivial forward model: linear in the unconstrained coordinates.

    Linear-Gaussian is the only case with a closed-form posterior, which is exactly why the
    engine is verified on it. The physics forward models are non-linear; testing the
    optimiser against them would confound optimiser error with model complexity and leave
    neither measured.
    """
    design = np.arange(1.0, 9.0)
    return np.array([float(design @ u), float(u @ u)])


class TestTheObjective:
    def test_it_is_the_negative_log_posterior_not_just_the_likelihood(self) -> None:
        # Dropping the prior is the commonest way this goes wrong, and the result still
        # converges — to the maximum-likelihood estimate, silently relabelled as MAP.
        prior = default_control_prior()
        u = np.asarray(prior.median().to_unconstrained())

        def log_likelihood(_: np.ndarray) -> float:
            return -1.5

        value = negative_log_posterior(u, log_likelihood=log_likelihood, prior=prior)

        assert value == pytest.approx(-(-1.5 + prior.log_prob_unconstrained(u)))

    def test_it_includes_the_log_jacobian_through_the_prior(self) -> None:
        # log_prob_unconstrained already carries the Jacobian. This asserts the objective
        # uses that rather than the constrained log_prob, because the difference is a
        # smooth bias that no convergence diagnostic would flag.
        prior = default_control_prior()
        u = np.asarray(prior.median().to_unconstrained())

        constrained = prior.log_prob(ControlParameters.from_unconstrained(u))
        unconstrained = prior.log_prob_unconstrained(u)
        assert constrained != pytest.approx(unconstrained), "the test is vacuous if these agree"

        value = negative_log_posterior(u, log_likelihood=lambda _: 0.0, prior=prior)

        assert value == pytest.approx(-unconstrained)

    def test_a_point_outside_the_support_is_infinite_rather_than_an_error(self) -> None:
        # L-BFGS-B evaluates trial points, and a bounded prior will be stepped outside.
        # Raising there aborts the optimisation; +inf tells the line search to back off.
        prior = default_control_prior()
        u = np.full(8, 1e6)

        value = negative_log_posterior(u, log_likelihood=lambda _: 0.0, prior=prior)

        assert np.isposinf(value) or value > 1e6


class TestTheGradient:
    @pytest.mark.physics
    def test_the_supplied_gradient_matches_a_finite_difference(self) -> None:
        # The defect that makes L-BFGS-B converge to a point that is not a stationary point
        # of the reported objective. Checked in unconstrained space, where the optimiser
        # actually works.
        prior = default_control_prior()
        u0 = np.asarray(prior.median().to_unconstrained())
        target = _quadratic_forward(u0) + 0.3

        def log_likelihood(u: np.ndarray) -> float:
            residual = _quadratic_forward(u) - target
            return float(-0.5 * residual @ residual)

        analytic = maximum_a_posteriori(
            log_likelihood=log_likelihood, prior=prior, initial=u0, max_iterations=0
        ).gradient

        step = 1e-6
        numerical = np.empty_like(u0)
        for i in range(u0.size):
            plus, minus = u0.copy(), u0.copy()
            plus[i] += step
            minus[i] -= step
            numerical[i] = (
                negative_log_posterior(plus, log_likelihood=log_likelihood, prior=prior)
                - negative_log_posterior(minus, log_likelihood=log_likelihood, prior=prior)
            ) / (2 * step)

        np.testing.assert_allclose(analytic, numerical, rtol=1e-4, atol=1e-6)


class TestClosedFormRecovery:
    """A linear-Gaussian problem, where the posterior mode is known analytically."""

    @pytest.mark.physics
    def test_it_finds_the_analytic_posterior_mode(self) -> None:
        # For y = A u + eps with eps ~ N(0, s^2 I) and a N(m, S) prior, the posterior mode
        # is (A'A/s^2 + S^-1)^-1 (A'y/s^2 + S^-1 m). Written out here independently of the
        # engine, so agreement is evidence rather than a tautology.
        rng = np.random.default_rng(20260806)
        n = 4
        design = rng.normal(size=(6, n))
        sigma = 0.5
        prior_mean = np.zeros(n)
        prior_var = 2.0
        truth = rng.normal(size=n)
        observed = design @ truth

        precision = design.T @ design / sigma**2 + np.eye(n) / prior_var
        expected = np.linalg.solve(
            precision, design.T @ observed / sigma**2 + prior_mean / prior_var
        )

        def log_likelihood(u: np.ndarray) -> float:
            r = design @ u - observed
            return float(-0.5 * r @ r / sigma**2)

        class GaussianPrior:
            def log_prob_unconstrained(self, u: np.ndarray) -> float:
                return float(-0.5 * (u - prior_mean) @ (u - prior_mean) / prior_var)

        result = maximum_a_posteriori(
            log_likelihood=log_likelihood,
            prior=GaussianPrior(),  # type: ignore[arg-type]
            initial=np.zeros(n),
        )

        np.testing.assert_allclose(result.unconstrained, expected, rtol=1e-6, atol=1e-8)

    @pytest.mark.physics
    def test_a_tighter_prior_pulls_the_estimate_toward_the_prior_mean(self) -> None:
        # The behaviour that distinguishes MAP from maximum likelihood. If the prior were
        # being dropped, this test would fail while every convergence check still passed.
        rng = np.random.default_rng(7)
        design = rng.normal(size=(3, 2))
        observed = design @ np.array([2.0, -2.0])

        def log_likelihood(u: np.ndarray) -> float:
            r = design @ u - observed
            return float(-0.5 * r @ r / 0.25)

        def solve(prior_var: float) -> np.ndarray:
            class P:
                def log_prob_unconstrained(self, u: np.ndarray) -> float:
                    return float(-0.5 * u @ u / prior_var)

            return maximum_a_posteriori(
                log_likelihood=log_likelihood,
                prior=P(),  # type: ignore[arg-type]
                initial=np.zeros(2),
            ).unconstrained

        loose = np.linalg.norm(solve(100.0))
        tight = np.linalg.norm(solve(0.01))

        assert tight < loose


class TestTheT0Contract:
    @pytest.mark.physics
    def test_noiseless_data_from_the_model_recovers_the_generating_parameters(self) -> None:
        # doc 05 §7.2's T0: same model, no noise, "recovery to numerical tolerance".
        # This is the engine's half of that contract.
        prior = default_control_prior()
        truth = np.asarray(prior.median().to_unconstrained())
        observed = _quadratic_forward(truth)

        def log_likelihood(u: np.ndarray) -> float:
            r = _quadratic_forward(u) - observed
            return float(-0.5 * r @ r / 1e-8)

        result = maximum_a_posteriori(
            log_likelihood=log_likelihood, prior=prior, initial=truth + 0.05
        )

        # Two observations cannot pin eight parameters; the prior fixes the rest. What must
        # hold is that the *data-constrained* directions are recovered and the fit is exact.
        np.testing.assert_allclose(_quadratic_forward(result.unconstrained), observed, rtol=1e-5)

    def test_it_starts_from_the_prior_median_by_default_not_the_reference(self) -> None:
        # The trap the priors layer documented: eedf.kappa's RP-1 nominal sits exactly on
        # the edge of its uniform [1,5] support, so reference().to_unconstrained() is -inf
        # and an engine initialised there initialises nowhere.
        prior = default_control_prior()

        result = maximum_a_posteriori(log_likelihood=lambda _: 0.0, prior=prior)

        assert np.all(np.isfinite(result.unconstrained))


class TestTheResult:
    def test_it_reports_the_constrained_parameters_as_well(self) -> None:
        # Callers reason about eV and m^-3, not about logits. Returning only the
        # unconstrained vector invites an inverse transform at every call site, and one of
        # them will get it wrong.
        prior = default_control_prior()

        result: MapResult = maximum_a_posteriori(log_likelihood=lambda _: 0.0, prior=prior)

        assert isinstance(result.parameters, ControlParameters)
        np.testing.assert_allclose(
            result.parameters.to_unconstrained(), result.unconstrained, rtol=1e-12
        )

    def test_it_reports_whether_the_optimiser_converged(self) -> None:
        # A MAP that silently returns the iteration limit is how a bad fit becomes a
        # published number.
        prior = default_control_prior()

        result = maximum_a_posteriori(log_likelihood=lambda _: 0.0, prior=prior)

        assert result.converged is True
        assert result.iterations >= 0

    def test_a_hopeless_problem_reports_failure_rather_than_pretending(self) -> None:
        def nan_likelihood(_: np.ndarray) -> float:
            return float("nan")

        result = maximum_a_posteriori(
            log_likelihood=nan_likelihood, prior=default_control_prior(), max_iterations=3
        )

        assert result.converged is False

    def test_it_is_immutable(self) -> None:
        result = maximum_a_posteriori(log_likelihood=lambda _: 0.0, prior=default_control_prior())

        with pytest.raises(AttributeError):
            result.converged = False  # type: ignore[misc]
